apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: muchtodo
data:
  SERVER_PORT: "8080"
  MONGO_URI: "mongodb://root:rootpassword@mongodb:27017/muchtodo?authSource=admin"
  DB_NAME: "muchtodo"
  ENABLE_CACHE: "false"
  JWT_EXPIRATION_HOURS: "24"
